stages:
  - test
  - deploy

before_script:
  - apk update
  - apk add curl git bash neovim
  - apk add make python3
  - curl -sSL https://bootstrap.pypa.io/get-pip.py | python3

test-latest:
  stage: test
  image:
    name: thinca/vim:latest-full
    entrypoint: [""]
  variables:
    MYVIM: vim -T dumb --not-a-term -n
  script: cd ./test/new && make -j1 && make -j1 coverage
  artifacts:
    reports:
      cobertura: ./test/new/coverage.xml

test-8.0.1575:
  stage: test
  image:
    name: thinca/vim:v8.0.1575-full
    entrypoint: [""]
  variables:
    MYVIM: vim -T dumb --not-a-term -n
  script: cd ./test/new && make -j1

test-7.4.2273:
  stage: test
  image:
    name: thinca/vim:v7.4.2273-full
    entrypoint: [""]
  variables:
    MYVIM: vim -T dumb --not-a-term -n
  script: cd ./test/new && make -j1

pages:
  stage: deploy
  script:
    - mv test/new/htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
    - dev-test-ts-split
