stages:
  - test
  - gen_coverage
  - deploy

.setup:
  before_script:
    - apk update
    - apk add curl git bash make
    - apk add neovim python3
    - curl -sSL https://bootstrap.pypa.io/get-pip.py | python3

test-latest:
  stage: test
  extends: .setup
  image:
    name: thinca/vim:latest-full
    entrypoint: [""]
  variables:
    MYVIM: vim -T dumb --not-a-term -n
  script: cd ./test/new && make -j1
  artifacts:
    paths:
      - ./test/new/cov.tmp/

test-8.0.1575:
  stage: test
  extends: .setup
  image:
    name: thinca/vim:v8.0.1575-full
    entrypoint: [""]
  variables:
    MYVIM: vim -T dumb --not-a-term -n
  script: cd ./test/new && make -j1
  artifacts:
    paths:
      - ./test/new/cov.tmp/

test-7.4.2273:
  stage: test
  extends: .setup
  image:
    name: thinca/vim:v7.4.2273-full
    entrypoint: [""]
  variables:
    MYVIM: vim -T dumb --not-a-term -n
  script: cd ./test/new && make -j1
  artifacts:
    paths:
      - ./test/new/cov.tmp/

test-neovim:
  stage: test
  extends: .setup
  image: alpine:latest
  script: cd ./test/new && make -j1
  artifacts:
    paths:
      - ./test/new/cov.tmp/

coverage:
  stage: gen_coverage
  script: cd ./test/new && make -j1 coverage
  artifacts:
    reports:
      cobertura: ./test/new/coverage.xml

pages:
  stage: deploy
  image: ruby:2.3
  script:
    - mkdir public
    - mv ./test/new/htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  dependencies:
    - coverage
  only:
    - master
    - dev-test-ts-split
